version: '3.8'

services:
  # Application WebKlor
  webklor:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend API
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/webklor
      - JWT_SECRET=WebKlor2025SecureSecretKey32CharactersLong!
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - webklor-network
    restart: unless-stopped

  # Base de données MongoDB
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=webklor
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - webklor-network
    restart: unless-stopped

  # Interface d'administration MongoDB (optionnel)
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - webklor-network
    restart: unless-stopped

networks:
  webklor-network:
    driver: bridge

volumes:
  mongodb_data:
